// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-api-clients-go/v2/cantabular"
	"github.com/ONSdigital/dp-cantabular-metadata-extractor-api/api"
	"sync"
)

// Ensure, that CantExtAPIMock does implement api.CantExtAPI.
// If this is not the case, regenerate this file with moq.
var _ api.CantExtAPI = &CantExtAPIMock{}

// CantExtAPIMock is a mock implementation of api.CantExtAPI.
//
// 	func TestSomethingThatUsesCantExtAPI(t *testing.T) {
//
// 		// make and configure a mocked api.CantExtAPI
// 		mockedCantExtAPI := &CantExtAPIMock{
// 			GetMetadataDatasetFunc: func(cantDataset string, dimensions []string) (*cantabular.MetadataDatasetQuery, error) {
// 				panic("mock out the GetMetadataDataset method")
// 			},
// 			GetMetadataTableFunc: func(datasetID string) (*cantabular.MetadataTableQuery, []string, error) {
// 				panic("mock out the GetMetadataTable method")
// 			},
// 		}
//
// 		// use mockedCantExtAPI in code that requires api.CantExtAPI
// 		// and then make assertions.
//
// 	}
type CantExtAPIMock struct {
	// GetMetadataDatasetFunc mocks the GetMetadataDataset method.
	GetMetadataDatasetFunc func(cantDataset string, dimensions []string) (*cantabular.MetadataDatasetQuery, error)

	// GetMetadataTableFunc mocks the GetMetadataTable method.
	GetMetadataTableFunc func(datasetID string) (*cantabular.MetadataTableQuery, []string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetMetadataDataset holds details about calls to the GetMetadataDataset method.
		GetMetadataDataset []struct {
			// CantDataset is the cantDataset argument value.
			CantDataset string
			// Dimensions is the dimensions argument value.
			Dimensions []string
		}
		// GetMetadataTable holds details about calls to the GetMetadataTable method.
		GetMetadataTable []struct {
			// DatasetID is the datasetID argument value.
			DatasetID string
		}
	}
	lockGetMetadataDataset sync.RWMutex
	lockGetMetadataTable   sync.RWMutex
}

// GetMetadataDataset calls GetMetadataDatasetFunc.
func (mock *CantExtAPIMock) GetMetadataDataset(cantDataset string, dimensions []string) (*cantabular.MetadataDatasetQuery, error) {
	if mock.GetMetadataDatasetFunc == nil {
		panic("CantExtAPIMock.GetMetadataDatasetFunc: method is nil but CantExtAPI.GetMetadataDataset was just called")
	}
	callInfo := struct {
		CantDataset string
		Dimensions  []string
	}{
		CantDataset: cantDataset,
		Dimensions:  dimensions,
	}
	mock.lockGetMetadataDataset.Lock()
	mock.calls.GetMetadataDataset = append(mock.calls.GetMetadataDataset, callInfo)
	mock.lockGetMetadataDataset.Unlock()
	return mock.GetMetadataDatasetFunc(cantDataset, dimensions)
}

// GetMetadataDatasetCalls gets all the calls that were made to GetMetadataDataset.
// Check the length with:
//     len(mockedCantExtAPI.GetMetadataDatasetCalls())
func (mock *CantExtAPIMock) GetMetadataDatasetCalls() []struct {
	CantDataset string
	Dimensions  []string
} {
	var calls []struct {
		CantDataset string
		Dimensions  []string
	}
	mock.lockGetMetadataDataset.RLock()
	calls = mock.calls.GetMetadataDataset
	mock.lockGetMetadataDataset.RUnlock()
	return calls
}

// GetMetadataTable calls GetMetadataTableFunc.
func (mock *CantExtAPIMock) GetMetadataTable(datasetID string) (*cantabular.MetadataTableQuery, []string, error) {
	if mock.GetMetadataTableFunc == nil {
		panic("CantExtAPIMock.GetMetadataTableFunc: method is nil but CantExtAPI.GetMetadataTable was just called")
	}
	callInfo := struct {
		DatasetID string
	}{
		DatasetID: datasetID,
	}
	mock.lockGetMetadataTable.Lock()
	mock.calls.GetMetadataTable = append(mock.calls.GetMetadataTable, callInfo)
	mock.lockGetMetadataTable.Unlock()
	return mock.GetMetadataTableFunc(datasetID)
}

// GetMetadataTableCalls gets all the calls that were made to GetMetadataTable.
// Check the length with:
//     len(mockedCantExtAPI.GetMetadataTableCalls())
func (mock *CantExtAPIMock) GetMetadataTableCalls() []struct {
	DatasetID string
} {
	var calls []struct {
		DatasetID string
	}
	mock.lockGetMetadataTable.RLock()
	calls = mock.calls.GetMetadataTable
	mock.lockGetMetadataTable.RUnlock()
	return calls
}
