---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17

inputs:
  - name: dp-cantabular-metadata-extractor-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-cantabular-metadata-extractor-api/ci/scripts/build.sh
